### ISSUE TITLE
네이버 아이디로 로그인 추가 후 실행시 app 튕김 현상

### ISSUE THREAD

**Issue by b1ctory** [NewdealDev1Team/DDUBUCK#1]
아래의 로그가 찍히며 Application 자체가 종료되어버리는 문제 발생

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.ddubuck, PID: 8461
    java.lang.RuntimeException: Unable to destroy activity {com.example.ddubuck/com.nhn.android.naverlogin.ui.OAuthLoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nhn.android.naverlogin.OAuthLoginHandler.run(boolean)' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5111)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nhn.android.naverlogin.OAuthLoginHandler.run(boolean)' on a null object reference
        at com.nhn.android.naverlogin.ui.OAuthLoginActivity.onDestroy(OAuthLoginActivity.java:138)
        at android.app.Activity.performDestroy(Activity.java:8245)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5096)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) `

**Comment by b1ctory** [comment]
mContext 변수를 초기화해주지 않아서 생긴 문제
onCreate메소드 안에 mContext = this 라인 추가 후 오류 해결
